### ISSUE TITLE
Problems with my corpus on the Test Platform

### ISSUE THREAD

**Issue by abravo84** [openminted/Open-Call-Discussions#14]
Hello!!!

I have a problem when I go to My Corpora. Currently, I have one corpus:

https://test.openminted.eu/landingPage/corpus/cb6b89a1-1e4f-4ba8-b790-9ce74e5d8a08

It is a zip file containing 5 xml files. When I download my corpus, the zip file is empty. Then, I try to edit my corpus in order to upload the zip file again, but I do not see the pencil icon to edit my corpus in the "Actions" column.

Best,

àlex.

**Comment by antleb** [comment]
Once you've made your corpus public, you can no longer edit its metadata or upload a new zip file. Regarding the empty zip file, my guess is that you uploaded a zip file not in the correct structure. Please, check the guidelines on the zip structure.

**Comment by galanisd** [comment]
For this corpus which I think was created by you 
https://test.openminted.eu/landingPage/corpus/a31a528f-7489-4fa9-8397-e4110f88d570
the zip was not empty. A couple weeks ago I was using it for testing Chebi service. 
From last week till now when I try to download it I get a corrupted zip.

**Comment by greenwoodma** [comment]
Both corpora appear to be empty (the first is an empty zip, the second a 0 byte file). While this is unfortunate, given how many changes to the test platform have happened since these were originally uploaded it's pretty much impossible to figure out what might have happened. I'm going to close this issue, but if anyone sees the same problem in the future please create a new issue and we'll take another look.
