### ISSUE TITLE
Questions about component registration

### ISSUE THREAD

**Issue by AndreLamurias** [openminted/Open-Call-Discussions#26]
We have registered our component on the OpenMinTeD platform. How can we check if it has been correctly implemented and integrated? We are sharing it as a docker contain, while the code is written in python. 

Also, our component is a deep learning model, so it can be used both to train a classifier or to predict new relations using a pre-trained classifier. How can we specify this in the input and output metadata?

Thanks,
André Lamúrias

**Comment by gkirtzou** [comment]
In order to test your component you need 2 things:
1. Create a meaningful  application using your component.  You could just add only your component if that makes sense and the editor will add the necessary steps of OMTD importer in order to generate a runnable application. You can do using the workflow editor, which can be found at Add->Application->Build an application with existing components
2. You need to either upload or create a meaningful small corpus data.  
Then with the newly created application and the sample corpus you can test your component, using the prediction functionality of your component.

As far your second question is concerned, given the metadata schema, you would need to register the component twice in order to define its two distinct functionalities. I imagine that for the first functionality, i.e. train a classifier, the input is a corpus and the output a language description (under this term the ML model is described in the metadata schema), while for the second functionality, i.e. predicting new relation using a pre-trained classifier, you would have as input again a corpus probably, as output either an annotated corpus or a document with the extracted relations, while the pre-trained model could be defined in the parameterInfo section. 

Katerina

**Comment by galanisd** [comment]
Closing it since the discussion was moved here
https://github.com/openminted/Open-Call-Discussions/issues/32
