### ISSUE TITLE
OMTD takes a long time to send request to web service

### ISSUE THREAD

**Issue by Aequivinius** [openminted/Open-Call-Discussions#41]
We've registered our NER pipeline as a webservice (https://test.openminted.eu/landingPage/application/b8fb9bbd-603c-4b53-b86d-15c6c753302d)

I realised today that OMTD takes a long time from the point of time when I launch a process (hitting "run" after selecting application and input corpus) to the point of time when the first request from OMTD is sent to our webservice: When I tried it around 14:30 today, it took about 5m. However, since then I've tried again and haven't received any request even after waiting for 15m. Is there some problem with the OMTD servers?

Also, I noticed that you're sending a lot of GET /process/ request once started, about one per second for 5m for the same process-ID. Is this intended?

**Comment by galanisd** [comment]
> We've registered our NER pipeline as a webservice (https://test.openminted.eu/landingPage/application/b8fb9bbd-603c-4b53-b86d-15c6c753302d)
> 
> I realised today that OMTD takes a long time from the point of time when I launch a process (hitting "run" after selecting application and input corpus) to the point of time when the first request from OMTD is sent to our webservice: When I tried it around 14:30 today, it took about 5m. 

Before starting calling the web service there are also 2 other components that have to run. The first fetches the data from our storage, the second converts pdfs to xmi format. From my logs it seems that 5 minutes is a reasonable amount of time for this setup. The production setup I think will be faster.

> However, since then I've tried again and haven't received any request even after waiting for 15m. Is there some problem with the OMTD servers?

Just tried with thalamus corpus. Got results. So probably you got some requests. Please can check?

> Also, I noticed that you're sending a lot of GET /process/ request once started, about one per second for 5m for the same process-ID. Is this intended?

You should ask @nguyennth for this because University Of Manchester has created the web service spec.
that you are using.

**Comment by Aequivinius** [comment]
@galanisd I got requests yesterday at 2247, so it seems to work again!
